spring:
  datasource:
    username: admin
    password: password
    url: jdbc:h2:mem:kul-logistics-db
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false